version: '3'

services:
  db:
    image: mysql:8.0.23
    ports:
      - 4306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    command: /bin/bash -c "
        rm -rf tmp/pids/server.pid &&
        bundle exec rails db:migrates &&
        bundle exec rails s -u webrick -p 3000 -b '0.0.0.0'"
    # volumes:
    #   - ./api:/myapp
    #   - ./api/vendor/bundle:/myapp/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "8000:3000"
volumes:
  postgres-data:
    driver: local
