version: '3'

services:
  db:
    image: mysql:8.0.23
    ports:
      - 3308:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    command: /bin/bash -c "
        rm -rf tmp/pids/server.pid &&
        bundle exec rails db:migrate &&
        bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    command: sh -c "yarn start"
    ports:
      - "8000:3000"
volumes:
  mysql-data:
    driver: local
